// This file was generated by py/makeversionhdr.py
static  MANSFIELD_GIT_TAG: &str = "728cc3c-dirty";
//static  MANSFIELD_GIT_HASH: &str = "728cc3c-dirty";
static  MANSFIELD_BUILD_DATE: &str = "2018-04-03";
//static  MANSFIELD_VERSION_MAJOR: (0)
//static  MANSFIELD_VERSION_MINOR: (0)
//static  MANSFIELD_VERSION_MICRO: (1)
//static  MANSFIELD_VERSION_STRING: &str = "0.0.1"
